name: lumea_alessiei
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.9.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animations: ^2.0.11
  audioplayers: ^6.0.0
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  intl: 0.20.2
  rive: ^0.13.20
  shared_preferences: ^2.2.3
  video_player: ^2.8.6
  flutter_midi: ^1.1.0
  piano: 1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/games_module/puzzle_game/
    - assets/images/games_module/sorting_animals_game/
    - assets/images/games_module/instruments_game/
    - assets/images/sounds_module/categories/
    - assets/audio/sunete/
    - assets/audio/sunete/ferma/
    - assets/audio/sunete/salbatice/
    - assets/audio/sunete/pasari/
    - assets/audio/sunete/marine/
    - assets/audio/sunete/vehicule/
    - assets/audio/cantece/
    - assets/video/povesti/
    - assets/data/
    - assets/privacy/
    - assets/rive_3d/
    - assets/images/menu/
    - assets/images/sounds/
    - assets/images/songs_module/
    - assets/images/stories_module/
    - assets/images/games_module/memory_cards/
    - assets/images/games_module/puzzle_levels/
    - assets/images/sounds_module/ferma/
    - assets/images/sounds_module/marine/
    - assets/images/sounds_module/pasari/
    - assets/images/sounds_module/vehicule/
    - assets/images/sounds_module/salbatice/
    - assets/audio/instrumente/
    - assets/audio/instrumente/xilofon/
    - assets/audio/instrumente/tobe/
    - assets/video/menu/
    - assets/video/sounds/
    # Rive assets
    - assets/rive/birds.riv
    - assets/rive/ferma.riv
    - assets/rive/title.riv
    - assets/rive/marine.riv
    - assets/rive/pasari.riv
    - assets/rive/vehicule.riv
    - assets/rive/salbatice.riv
    - assets/rive/game_buttons.riv
    - assets/rive/menu_buttons.riv
    - assets/rive/song_buttons.riv
    - assets/rive/story_buttons.riv
    # Soundfont for MIDI
    - assets/sf2/
